import { defineConfig } from "tsdown";

export default defineConfig({
  entry: [
    "src/easing.ts",
    "src/math.ts",
    "src/color.ts",
    "src/date.ts",
    "src/text.ts",
    "src/css.ts",
    "src/responsive.ts",
    "src/alea.ts",
    "src/subtitle.ts",
    "src/presets.ts",
    "src/code.ts",
    "src/cue/index.ts",
    "src/score.ts",
    "src/backgrounds.ts",
    "src/montage.ts",
    "src/spring.ts",
    "src/stagger.ts",
    "src/interpolate.ts",
    "src/path.ts",
    "src/svg/index.ts",
    "src/layout.ts",
    "src/layers.ts",
    "src/safe-area.ts",
    "src/video.ts",
    "src/reveal.ts",
    "src/oscillate.ts",
    "src/viz/index.ts",
    "src/index.ts",
  ],
  format: ["esm"],
  dts: true,
  outDir: "dist",
  clean: true,
  deps: {
    alwaysBundle: ["date-fns", "colord", "simplex-noise", "shiki", "@shikijs/themes", "@shikijs/langs", "path-data-parser", "katex"],
  },
  outExtensions: () => ({ js: '.js', dts: '.d.ts' }),
});
