import { defineConfig } from "tsdown";
import { libraryDefaults } from "../build-policy/tsdown.base.ts";

export default defineConfig({
  ...libraryDefaults,
  entry: [
    "src/easing.ts",
    "src/math.ts",
    "src/color.ts",
    "src/date.ts",
    "src/text.ts",
    "src/css.ts",
    "src/responsive.ts",
    "src/alea.ts",
    "src/subtitle.ts",
    "src/presets.ts",
    "src/code.ts",
    "src/cue/index.ts",
    "src/director.ts",
    "src/carousel.ts",
    "src/stack.ts",
    "src/track.ts",
    "src/backgrounds.ts",
    "src/montage.ts",
    "src/spring.ts",
    "src/stagger.ts",
    "src/interpolate.ts",
    "src/path.ts",
    "src/svg/index.ts",
    "src/layout.ts",
    "src/layers.ts",
    "src/safe-area.ts",
    "src/video.ts",
    "src/media.ts",
    "src/reveal.ts",
    "src/oscillate.ts",
    "src/viz/index.ts",
    "src/index.ts",
  ],
  outDir: "dist",
  clean: true,
  deps: {
    alwaysBundle: [
      /^date-fns($|\/)/,
      /^colord($|\/)/,
      "simplex-noise",
      /^shiki($|\/)/,
      /^@shikijs\//,
      "path-data-parser",
      "katex",
      "d3-array",
      "d3-format",
      "d3-regression",
      "d3-hierarchy",
      "d3-contour",
      "d3-density",
      "d3-force",
      "d3-scale",
      "d3-shape",
    ],
  },
});
