//! Generate browser runtime code from TypeScript sources
//!
//! Bundles compose, scene, utils, transitions into a single JS string
//! that the bundler plugin injects for `import "superimg"` in templates.
//!
//! Run: pnpm run generate

import * as esbuild from "esbuild";
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const srcDir = join(__dirname, "..", "src");
const generatedDir = join(srcDir, "generated");

// Entry code that exports what templates need
const entryCode = `
// Identity functions for type inference
export function defineScene(m) { return m; }
export function defineConfig(c) { return c; }

// Real implementations from source
export { compose } from "./composition/compose.js";
export { scene } from "./composition/scene.js";
`;

async function main() {
  console.log("Generating browser runtime code...");

  const result = await esbuild.build({
    stdin: {
      contents: entryCode,
      resolveDir: srcDir,
      loader: "ts",
    },
    bundle: true,
    format: "esm",
    platform: "neutral",
    target: "es2020",
    write: false,
    minify: false, // Keep readable for debugging
    // Types get stripped, stdlib is accessed via ctx.std at runtime
    external: ["@superimg/types"],
  });

  if (result.errors.length > 0) {
    console.error("Build errors:", result.errors);
    process.exit(1);
  }

  const code = result.outputFiles[0].text;

  // Ensure generated directory exists
  mkdirSync(generatedDir, { recursive: true });

  // Write the generated TypeScript file
  const outputPath = join(generatedDir, "runtime-code.ts");
  writeFileSync(
    outputPath,
    `// Auto-generated by scripts/generate-runtime.ts
// DO NOT EDIT - regenerate with: pnpm run generate
//
// This is the bundled runtime code for browser template compilation.
// Templates that import from "superimg" get this code injected.

export const RUNTIME_CODE = ${JSON.stringify(code)};
`
  );

  console.log(`Generated: ${outputPath}`);
  console.log(`Code size: ${code.length} bytes`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
