//! Generate browser runtime code from TypeScript sources
//!
//! Bundles compose, scene, utils, transitions into a single JS string
//! that the bundler plugin injects for `import "superimg"` in templates.
//!
//! Run: pnpm run generate

import { rolldown } from "rolldown";
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const srcDir = join(__dirname, "..", "src");
const generatedDir = join(srcDir, "generated");

// Entry code that exports what templates need
const entryCode = `
// Unified template factory. medium + animated are derived statically; the same
// values the metadata extractor reads from the config literal.
export function define(input) {
  const medium = input && input.medium ? input.medium : "html";
  const c = input ? input.config : undefined;
  const animated = !!c && typeof c.fps === "number" && c.duration != null;
  return { ...input, medium, animated };
}
export function defineConfig(c) { return c; }
// Returns the provider unchanged — used only at module init for batch exports.
export function defineBatch(_template, provider) { return provider; }

// Real implementations from source
export { compose } from "./composition/compose.js";
export { scene } from "./composition/scene.js";
`;

async function main() {
  console.log("Generating browser runtime code...");

  const entryId = resolve(srcDir, "runtime-entry.ts");
  const bundle = await rolldown({
    input: entryId,
    external: ["@superimg/types"],
    plugins: [
      {
        name: "stdin",
        resolveId(id) {
          return id === entryId ? entryId : null;
        },
        load(id) {
          return id === entryId ? entryCode : null;
        },
      },
    ],
  });

  let code: string;
  try {
    const { output } = await bundle.generate({ format: "es" });
    code = output[0]!.code;
  } finally {
    await bundle.close();
  }

  // Ensure generated directory exists
  mkdirSync(generatedDir, { recursive: true });

  // Write the generated TypeScript file
  const outputPath = join(generatedDir, "runtime-code.ts");
  writeFileSync(
    outputPath,
    `// Auto-generated by scripts/generate-runtime.ts
// DO NOT EDIT - regenerate with: pnpm run generate
//
// This is the bundled runtime code for browser template compilation.
// Templates that import from "superimg" get this code injected.

export const RUNTIME_CODE = ${JSON.stringify(code)};
`
  );

  console.log(`Generated: ${outputPath}`);
  console.log(`Code size: ${code.length} bytes`);

  const stdlibDist = join(__dirname, "..", "..", "superimg-stdlib", "dist");
  const stdlibSources = {
    code: readFileSync(join(stdlibDist, "code.js"), "utf8"),
    cue: readFileSync(join(stdlibDist, "cue", "index.js"), "utf8"),
    text: readFileSync(join(stdlibDist, "text.js"), "utf8"),
  };

  const stdlibOutputPath = join(generatedDir, "stdlib-sources.ts");
  writeFileSync(
    stdlibOutputPath,
    `// Auto-generated by scripts/generate-runtime.ts
// DO NOT EDIT - regenerate with: pnpm run generate
//
// ESM source served by the browser bundler plugin for direct @superimg/stdlib imports.

export const STDLIB_SOURCES = ${JSON.stringify(stdlibSources, null, 2)} as const;
`,
  );

  console.log(`Generated: ${stdlibOutputPath}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});