// Generate src/_generated.ts from the canonical skills/ directory at the repo root.
// Embeds SKILL.md (frontmatter stripped), references/*, and examples/* as TS string constants.
// Skill version is read from this package's package.json so version-bump-and-publish stays linked.

import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from "node:fs";
import { join, dirname, basename, extname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = join(__dirname, "..");
const REPO_ROOT = join(PKG_ROOT, "..", "..");
const SKILLS_ROOT = join(REPO_ROOT, "skills", "superimg");

interface Frontmatter {
  name: string;
  description: string;
}

function parseFrontmatter(raw: string): { frontmatter: Frontmatter; body: string } {
  const match = raw.match(/^---\n([\s\S]*?)\n---\n?\n?([\s\S]*)$/);
  if (!match) {
    throw new Error("SKILL.md is missing YAML frontmatter (--- header)");
  }
  const fmRaw = match[1] ?? "";
  const body = match[2] ?? "";

  const lines = fmRaw.split("\n");
  const result: Record<string, string> = {};
  let currentKey: string | null = null;
  let currentValue = "";

  for (const line of lines) {
    const keyMatch = line.match(/^([a-zA-Z_][a-zA-Z0-9_]*):\s*(.*)$/);
    if (keyMatch) {
      if (currentKey) {
        result[currentKey] = currentValue.trim();
      }
      currentKey = keyMatch[1] ?? null;
      const rest = keyMatch[2] ?? "";
      currentValue = rest === ">" || rest === "|" ? "" : rest;
    } else if (currentKey && line.trim()) {
      currentValue += (currentValue ? " " : "") + line.trim();
    }
  }
  if (currentKey) {
    result[currentKey] = currentValue.trim();
  }

  if (!result.name || !result.description) {
    throw new Error("SKILL.md frontmatter must include 'name' and 'description'");
  }

  return {
    frontmatter: { name: result.name, description: result.description },
    body: body.trim() + "\n",
  };
}

function readSkill(): { frontmatter: Frontmatter; body: string } {
  const path = join(SKILLS_ROOT, "SKILL.md");
  if (!existsSync(path)) {
    throw new Error(`Canonical skill not found at ${path}`);
  }
  return parseFrontmatter(readFileSync(path, "utf-8"));
}

function readDirRecord(dir: string, exts: string[]): Record<string, string> {
  if (!existsSync(dir)) return {};
  const entries = readdirSync(dir).filter((f) => exts.includes(extname(f)));
  const out: Record<string, string> = {};
  for (const f of entries) {
    const name = basename(f, extname(f));
    out[name] = readFileSync(join(dir, f), "utf-8");
  }
  return out;
}

function readPkgVersion(): string {
  const pkg = JSON.parse(readFileSync(join(PKG_ROOT, "package.json"), "utf-8"));
  if (typeof pkg.version !== "string") {
    throw new Error("@superimg/skill package.json missing version");
  }
  return pkg.version;
}

function escape(s: string): string {
  return JSON.stringify(s);
}

function generate(): string {
  const { frontmatter, body } = readSkill();
  const version = readPkgVersion();
  const references = readDirRecord(join(SKILLS_ROOT, "references"), [".md"]);
  const examples = readDirRecord(join(SKILLS_ROOT, "examples"), [".ts"]);

  const refEntries = Object.entries(references)
    .map(([k, v]) => `  ${escape(k)}: ${escape(v)},`)
    .join("\n");
  const exEntries = Object.entries(examples)
    .map(([k, v]) => `  ${escape(k)}: ${escape(v)},`)
    .join("\n");

  return `// AUTO-GENERATED by scripts/generate-content.ts. Do not edit.
// Source: <repo>/skills/superimg/

export const SKILL_VERSION = ${escape(version)};
export const SKILL_NAME = ${escape(frontmatter.name)};
export const SKILL_DESCRIPTION = ${escape(frontmatter.description)};
export const SKILL_BODY = ${escape(body)};

export const REFERENCES: Record<string, string> = {
${refEntries}
};

export const EXAMPLES: Record<string, string> = {
${exEntries}
};
`;
}

function main() {
  const out = generate();
  const dir = join(PKG_ROOT, "src");
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  writeFileSync(join(dir, "_generated.ts"), out);
  console.log(`@superimg/skill: generated _generated.ts (${out.length} bytes)`);
}

main();
