//! RSC-safe entry — template authoring only (define, types). No browser/CLI deps.

export type {
  RenderContext,
  OutputInfo,
  CssViewport,
  PlaybackMode,
  LoadMode,
  HoverBehavior,
  FitMode,
  Medium,
  AnyTemplateModule,
  TemplateModule,
  AnimatedTemplateModule,
  StaticTemplateModule,
  DefineInput,
  TemplateConfig,
  ProjectConfig,
  Duration,
  Transition,
  TransitionType,
  SceneDefinition,
  ResolvedScene,
  ResolvedTransition,
  ComposedTemplate,
  RenderOptions,
  EncodingOptions,
  OutputFormat,
  VideoCodecPreference,
  AudioCodecPreference,
  QualityPreset,
  AssetMeta,
  ImageAssetMeta,
  VideoAssetMeta,
  AudioAssetMeta,
  BackgroundValue,
  AudioValue,
  AudioClip,
  AudioTimeline,
  ResolvedAudioTimeline,
  BackgroundOptions,
  LoadResult,
  RenderResult,
  RenderBufferResult,
  Checkpoint,
  CheckpointSource,
  Marker,
  MarkerPosition,
  BatchEntry,
  BatchProvider,
  CompileError,
  CompileResult,
  Stdlib,
  ImageStdlib,
  SvgStdlib,
  SvgAnimatedStdlib,
  ImageRenderContext,
  SvgRenderContext,
  SvgAnimatedRenderContext,
} from "@superimg/types";

export {
  define,
  defineConfig,
  defineBatch,
  isAnimatedTemplate,
  isStaticTemplate,
  isComposedTemplate,
  isAnyComposedTemplate,
} from "@superimg/types";

export {
  SuperImgError,
  TemplateCompilationError,
  TemplateRuntimeError,
  ValidationError,
  RenderError,
  IOError,
} from "@superimg/types";

export {
  createRenderContext,
  createImageRenderContext,
  createSvgRenderContext,
  resolveRuntimeTemplateInfo,
  compileTemplate,
  validateTemplate,
  CheckpointResolver,
  compose,
  scene,
  transitions,
  parseDuration,
} from "@superimg/core";

export { buildCompositeHtml } from "@superimg/core/html";