#!/usr/bin/env node
// Reads the vite-built harness files and generates src/harness-assets.ts
// with the content inlined as string constants.

import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

const html = readFileSync(join(root, "dist", "harness", "index.html"), "utf-8");
const js = readFileSync(join(root, "dist", "harness", "harness.js"), "utf-8");

const out = [
  "// AUTO-GENERATED by scripts/embed-harness.mjs — do not edit",
  `export const HARNESS_HTML = ${JSON.stringify(html)};`,
  `export const HARNESS_JS = ${JSON.stringify(js)};`,
  "",
].join("\n");

writeFileSync(join(root, "src", "harness-assets.ts"), out);
console.log("Embedded harness assets into src/harness-assets.ts");
