import { readFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig } from "tsup";

const __dirname = dirname(fileURLToPath(import.meta.url));
const pkg = JSON.parse(readFileSync(resolve(__dirname, "package.json"), "utf8"));

export default defineConfig({
  entry: {
    index: "src/index.shared.ts",
    "index.browser": "src/index.browser.ts",
    "index.player": "src/index.player.ts",
    "index.bundler": "src/index.bundler.ts",
    "index.server": "src/index.server.ts",
    "react/index": "src/react/index.ts",
    "react/player": "src/react/player.ts",
    stdlib: "src/stdlib.ts",
    "stdlib/backgrounds": "../superimg-stdlib/src/backgrounds.ts",
    "stdlib/code": "../superimg-stdlib/src/code.ts",
    "stdlib/color": "../superimg-stdlib/src/color.ts",
    "stdlib/css": "../superimg-stdlib/src/css.ts",
    "stdlib/date": "../superimg-stdlib/src/date.ts",
    "stdlib/easing": "../superimg-stdlib/src/easing.ts",
    "stdlib/interpolate": "../superimg-stdlib/src/interpolate.ts",
    "stdlib/layout": "../superimg-stdlib/src/layout.ts",
    "stdlib/math": "../superimg-stdlib/src/math.ts",
    "stdlib/montage": "../superimg-stdlib/src/montage.ts",
    "stdlib/path": "../superimg-stdlib/src/path.ts",
    "stdlib/presets": "../superimg-stdlib/src/presets.ts",
    "stdlib/responsive": "../superimg-stdlib/src/responsive.ts",
    "stdlib/score": "../superimg-stdlib/src/score.ts",
    "stdlib/spring": "../superimg-stdlib/src/spring.ts",
    "stdlib/stagger": "../superimg-stdlib/src/stagger.ts",
    "stdlib/subtitle": "../superimg-stdlib/src/subtitle.ts",
    "stdlib/svg": "../superimg-stdlib/src/svg/index.ts",
    "stdlib/text": "../superimg-stdlib/src/text.ts",
    "stdlib/cue": "../superimg-stdlib/src/cue/index.ts",
    cli: "src/cli.ts",
  },
  format: ["esm"],
  dts: { resolve: true },
  clean: true,
  define: {
    __SUPERIMG_VERSION__: JSON.stringify(pkg.version),
  },
  noExternal: [
    "@superimg/cli",
    "@superimg/types",
    "@superimg/stdlib",
    /^@superimg\/core/,
    "@superimg/runtime",
    "@superimg/player",
    "@superimg/skill",
    "@superimg/playwright",
    "hono",
    "@hono/node-server",
    "zod",
  ],
  external: [
    "zustand",
    "date-fns",
    "colord",
    "simplex-noise",
    "playwright",
    "playwright-core",
    "esbuild",
    "esbuild-wasm",
    "commander",
    "acorn",
    "ink",
    "react",
    "vite",
    "ws",
    // Native binding packages must be external
    "oxc-parser",
    /^@oxc-parser\//,
  ],
  onSuccess: "rm -rf dist/dev-ui && cp -R ../superimg-cli/dist/dev-ui dist/dev-ui",
});
