#!/usr/bin/env npx tsx
/**
 * Generate playground examples from examples/templates/ folder
 * Reads .video.ts/.video.js files and outputs TypeScript with code as strings
 */

import * as fs from "fs";
import * as path from "path";

const TEMPLATES_DIR = path.join(__dirname, "../examples/templates");
const OUTPUT_FILE = path.join(
  __dirname,
  "../apps/docs/lib/video/examples/from-templates.ts"
);

interface TemplateMetadata {
  title: string;
  category: "getting-started" | "marketing" | "social" | "data" | "developer";
  description?: string;
}

// Read metadata
const metadataPath = path.join(TEMPLATES_DIR, "_metadata.json");
const metadata: Record<string, TemplateMetadata> = JSON.parse(
  fs.readFileSync(metadataPath, "utf-8")
);

// Find all single-file templates (skip multi-file like assets-demo)
const templateDirs = fs.readdirSync(TEMPLATES_DIR).filter((name) => {
  const dirPath = path.join(TEMPLATES_DIR, name);
  if (!fs.statSync(dirPath).isDirectory()) return false;
  if (name.startsWith("_")) return false;

  // Check for a single .video.ts/.video.js file directly in the folder
  const files = fs.readdirSync(dirPath);
  const videoFiles = files.filter(
    (f) => f.endsWith(".video.ts") || f.endsWith(".video.js")
  );
  return videoFiles.length === 1;
});

console.log(`Found ${templateDirs.length} templates:`, templateDirs);

// Read each template
const examples: Array<{
  id: string;
  title: string;
  category: string;
  code: string;
}> = [];

for (const dir of templateDirs) {
  const dirPath = path.join(TEMPLATES_DIR, dir);
  const files = fs.readdirSync(dirPath);
  const videoFile = files.find(
    (f) => f.endsWith(".video.ts") || f.endsWith(".video.js")
  );

  if (!videoFile) continue;

  const filePath = path.join(dirPath, videoFile);
  const code = fs.readFileSync(filePath, "utf-8");
  const meta = metadata[dir];

  if (!meta) {
    console.warn(`Warning: No metadata for ${dir}, skipping`);
    continue;
  }

  examples.push({
    id: dir,
    title: meta.title,
    category: meta.category,
    code,
  });

  console.log(`  ✓ ${dir} → ${meta.title} (${meta.category})`);
}

// Generate output file
const output = `// AUTO-GENERATED by scripts/generate-examples.ts
// Do not edit directly - edit examples/templates/ instead

import type { EditorExample } from "./index";

export const TEMPLATE_EXAMPLES: EditorExample[] = [
${examples
  .map(
    (ex) => `  {
    id: ${JSON.stringify(ex.id)},
    title: ${JSON.stringify(ex.title)},
    category: ${JSON.stringify(ex.category)},
    code: ${JSON.stringify(ex.code)},
  }`
  )
  .join(",\n")}
];
`;

fs.writeFileSync(OUTPUT_FILE, output);
console.log(`\nGenerated ${OUTPUT_FILE} with ${examples.length} examples`);
