#!/usr/bin/env npx tsx
/**
 * Generate playground examples from category folders under examples/
 * Reads .video.ts/.video.js files and outputs TypeScript with code as strings
 */

import * as fs from "fs";
import * as path from "path";

const EXAMPLES_DIR = path.join(__dirname, "../examples");
const METADATA_PATH = path.join(EXAMPLES_DIR, "_templates.json");
const OUTPUT_FILE = path.join(
  __dirname,
  "../apps/docs/lib/video/examples/from-templates.ts"
);

type TemplateCategory =
  | "basics"
  | "marketing"
  | "events"
  | "social"
  | "interfaces"
  | "data"
  | "vector"
  | "developer";

interface TemplateMetadata {
  title: string;
  category: TemplateCategory;
  description?: string;
}

// Read metadata
const metadata: Record<string, TemplateMetadata> = JSON.parse(
  fs.readFileSync(METADATA_PATH, "utf-8")
);

// Read each template
const examples: Array<{
  id: string;
  title: TemplateMetadata["title"];
  category: TemplateCategory;
  code: string;
}> = [];

for (const [id, meta] of Object.entries(metadata).sort(([a], [b]) =>
  a.localeCompare(b)
)) {
  const dirPath = path.join(EXAMPLES_DIR, meta.category, id);
  if (!fs.existsSync(dirPath) || !fs.statSync(dirPath).isDirectory()) {
    console.warn(`Warning: Missing directory for ${id} at ${dirPath}, skipping`);
    continue;
  }

  const files = fs.readdirSync(dirPath);
  const videoFiles = files.filter(
    (file) => file.endsWith(".video.ts") || file.endsWith(".video.js")
  );
  if (videoFiles.length !== 1) continue;

  const [videoFile] = videoFiles;
  const filePath = path.join(dirPath, videoFile);
  const code = fs.readFileSync(filePath, "utf-8");

  examples.push({
    id,
    title: meta.title,
    category: meta.category,
    code,
  });

  console.log(`  ✓ ${meta.category}/${id} → ${meta.title}`);
}

// Generate output file
const output = `// AUTO-GENERATED by scripts/generate-examples.ts
// Do not edit directly - edit examples/_templates.json and examples/<category>/ instead

import type { EditorExample } from "./index";

export const TEMPLATE_EXAMPLES: EditorExample[] = [
${examples
  .map(
    (ex) => `  {
    id: ${JSON.stringify(ex.id)},
    title: ${JSON.stringify(ex.title)},
    category: ${JSON.stringify(ex.category)},
    code: ${JSON.stringify(ex.code)},
  }`
  )
  .join(",\n")}
];
`;

fs.writeFileSync(OUTPUT_FILE, output);
console.log(`\nGenerated ${OUTPUT_FILE} with ${examples.length} examples`);
